TARGET=${THOR_HOME}/bin/thor_import
include ${THOR_HOME}/src/makefile.in

INCLUDES+=-I../../kernel 
INCLUDES+=-I../../common
INCLUDES+=-I${THOR_HOME}/add-ons

LIBS+=-L${THOR_HOME}/lib -lthorcommon -lthorkernel -lthorsql

