#define NEW_TK_SEMI                             1
#define NEW_TK_EXPLAIN                          2
#define NEW_TK_QUERY                            3
#define NEW_TK_PLAN                             4
#define NEW_TK_ID                               5
#define NEW_TK_INDEXED                          6
#define NEW_TK_ABORT                            7
#define NEW_TK_ACTION                           8
#define NEW_TK_AFTER                            9
#define NEW_TK_ANALYZE                         10
#define NEW_TK_ASC                             11
#define NEW_TK_ATTACH                          12
#define NEW_TK_BEFORE                          13
#define NEW_TK_BEGIN                           14
#define NEW_TK_BY                              15
#define NEW_TK_CASCADE                         16
#define NEW_TK_CAST                            17
#define NEW_TK_COLUMNKW                        18
#define NEW_TK_CONFLICT                        19
#define NEW_TK_DATABASE                        20
#define NEW_TK_DEFERRED                        21
#define NEW_TK_DESC                            22
#define NEW_TK_DETACH                          23
#define NEW_TK_EACH                            24
#define NEW_TK_END                             25
#define NEW_TK_EXCLUSIVE                       26
#define NEW_TK_FAIL                            27
#define NEW_TK_FOR                             28
#define NEW_TK_IGNORE                          29
#define NEW_TK_IMMEDIATE                       30
#define NEW_TK_INITIALLY                       31
#define NEW_TK_INSTEAD                         32
#define NEW_TK_LIKE_KW                         33
#define NEW_TK_MATCH                           34
#define NEW_TK_NO                              35
#define NEW_TK_KEY                             36
#define NEW_TK_OF                              37
#define NEW_TK_OFFSET                          38
#define NEW_TK_PRAGMA                          39
#define NEW_TK_RAISE                           40
#define NEW_TK_RECURSIVE                       41
#define NEW_TK_RELEASE                         42
#define NEW_TK_REPLACE                         43
#define NEW_TK_RESTRICT                        44
#define NEW_TK_ROW                             45
#define NEW_TK_ROLLBACK                        46
#define NEW_TK_SAVEPOINT                       47
#define NEW_TK_TEMP                            48
#define NEW_TK_TRIGGER                         49
#define NEW_TK_VACUUM                          50
#define NEW_TK_VIEW                            51
#define NEW_TK_VIRTUAL                         52
#define NEW_TK_WITH                            53
#define NEW_TK_WITHOUT                         54
#define NEW_TK_REINDEX                         55
#define NEW_TK_RENAME                          56
#define NEW_TK_CTIME_KW                        57
#define NEW_TK_IF                              58
#define NEW_TK_ANY                             59
#define NEW_TK_OR                              60
#define NEW_TK_AND                             61
#define NEW_TK_NOT                             62
#define NEW_TK_IS                              63
#define NEW_TK_BETWEEN                         64
#define NEW_TK_IN                              65
#define NEW_TK_ISNULL                          66
#define NEW_TK_NOTNULL                         67
#define NEW_TK_NE                              68
#define NEW_TK_EQ                              69
#define NEW_TK_GT                              70
#define NEW_TK_LE                              71
#define NEW_TK_LT                              72
#define NEW_TK_GE                              73
#define NEW_TK_ESCAPE                          74
#define NEW_TK_BITAND                          75
#define NEW_TK_BITOR                           76
#define NEW_TK_LSHIFT                          77
#define NEW_TK_RSHIFT                          78
#define NEW_TK_PLUS                            79
#define NEW_TK_MINUS                           80
#define NEW_TK_STAR                            81
#define NEW_TK_SLASH                           82
#define NEW_TK_REM                             83
#define NEW_TK_CONCAT                          84
#define NEW_TK_COLLATE                         85
#define NEW_TK_BITNOT                          86
#define NEW_TK_STRING                          87
#define NEW_TK_JOIN_KW                         88
#define NEW_TK_WHERE                           89
#define NEW_TK_UNION                           90
#define NEW_TK_ALL                             91
#define NEW_TK_EXCEPT                          92
#define NEW_TK_INTERSECT                       93
#define NEW_TK_SELECT                          94
#define NEW_TK_VALUES                          95
#define NEW_TK_LP                              96
#define NEW_TK_RP                              97
#define NEW_TK_COMMA                           98
#define NEW_TK_DISTINCT                        99
#define NEW_TK_DOT                            100
#define NEW_TK_AS                             101
#define NEW_TK_FROM                           102
#define NEW_TK_JOIN                           103
#define NEW_TK_ON                             104
#define NEW_TK_ORDER                          105
#define NEW_TK_GROUP                          106
#define NEW_TK_HAVING                         107
#define NEW_TK_LIMIT                          108
#define NEW_TK_NULL                           109
#define NEW_TK_INTEGER                        110
#define NEW_TK_FLOAT                          111
#define NEW_TK_BLOB                           112
#define NEW_TK_VARIABLE                       113
#define NEW_TK_EXISTS                         114
#define NEW_TK_CASE                           115
#define NEW_TK_WHEN                           116
#define NEW_TK_THEN                           117
#define NEW_TK_ELSE                           118
